<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'CDbTestFixture.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'Nekorekts CDbTestFixture.connectionID "{id}". Pārbaudiet vai tas norāda uz CDbConnection komponentes ID.',
  'Column "{column}" does not exist in table "{table}".' => 'Kolonna "{column}" neeksistē tabulā "{table}".',
  'Failed to set unsafe attribute "{attribute}".' => 'Neizdevās uzstādīt vērtību nedrošam atribūtam "{attribute}".',
  'Resetting PK sequence is not supported.' => 'Primārās atslēgas sekvences atgriešana netiek atbalstīta.',
  'Setting integrity check is not supported.' => 'Integritātes pārbaudes uzstādīšana netiek atbalstīta.',
  'The pattern for month must be "M", "MM", "MMM", "MMMM", "L", "LL", "LLL" or "LLLL".' => 'Mēneša sablonam ir jābūt "M", "MM", "MMM", "MMMM", "L", "LL", "LLL" vai "LLLL".',
  'The requested view "{name}" was not found.' => 'Pieprasītais skats "{name}" netika atrasts.',
  'Unknown type "{type}".' => 'Nezināms tips "{type}".',
  'Virtual attribute {name} must specify "asc" and "desc" options.' => 'Virtuālajam atribūtam "{name}" ir jābūt norādītām opcijām "asc" un "desc".',
  '{attribute} cannot accept more than {limit} files.' => '{attribute} nevar pieņemt vairāk kā {limit} failus.',      
  '"{path}" is not a valid directory.' => 'Ceļš "{path}" nav korekts direkotrijs.',
  '&lt; Previous' => '&lt; Iepriekšējā',
  '&lt;&lt; First' => '&lt;&lt; Pirmā',
  'Active Record requires a "db" CDbConnection application component.' => 'ActiveRecord klasēm ir nepieciešams, lai ir norādīta "db" CDbConnection komponente.',
  'Active record "{class}" has an invalid configuration for relation "{relation}". It must specify the relation type, the related active record class and the foreign key.' => 'ActiveRecord klasei "{class}" ir nekorekti nokonfigurēta relācija "{relation}". Jums ir jānorāda relācijas veids, relācijas mērķa ActivRecord klase un ārējā atslēga.',
  'Active record "{class}" is trying to select an invalid column "{column}". Note, the column must exist in the table or be an expression with alias.' => 'ActiveRecord "{class}" mēģina piekļūt neeksistējošai kolonnai "{column}". Atcerieties, kolonnai ir jāeksistē tabulā vai jābūt izteiksmei ar aizstājvārdu.',
  'Active record class "{class}" does not have a scope named "{scope}".' => 'ActiveRecord klasei "{class}" nav nosacījumu grupas ar nosaukumu "{scope}".',
  'Alias "{alias}" is invalid. Make sure it points to an existing directory or file.' => 'Neeksistējošs aizstājvārds "{alias}". Pārbaudiet, ka tas norāda uz eksistējošu direktoriju vai failu.',
  'Application base path "{path}" is not a valid directory.' => 'Lietojumprogrammas bāzes ceļš "(base)" nav korekts direktorijs.',
  'Application runtime path "{path}" is not valid. Please make sure it is a directory writable by the Web server process.' => 'Lietojumprogrammas izpildlaika ceļš "{path}" uzdots nekorekti. Pārbaudiet, ka direktorijs eksistē un ka tīmekļa servera procesam ir tiesības rakstīt norādītajā direktorijā.',
  'Authorization item "{item}" has already been assigned to user "{user}".' => 'Autorizācijas vienība "{item}" jau ir piešķirta lietotājam "{user}".',
  'Base path "{path}" is not a valid directory.' => 'Bāzes ceļš "{path}" nav korekts direktorijs.',
  'CApcCache requires PHP apc extension to be loaded.' => 'CApcCache nepieciešams, lai ir ielādēts PHP paplašinājums APC.',
  'CAssetManager.basePath "{path}" is invalid. Please make sure the directory exists and is writable by the Web server process.' => 'Ceļš CAssetManager.basePath "{path}" uzdots nekorekti. Pārbaudiet, ka direktorijs eksistē un ka tīmekļa servera procesam ir tiesības rakstīt norādītajā direktorijā.',
  'CCacheHttpSession.cacheID is invalid. Please make sure "{id}" refers to a valid cache application component.' => 'CCacheHttpSession.cacheID ir nekorekts. Pārbaudiet, ka "{id}" norāda uz korektu kešatmiņas komponenti.',
  'CCaptchaValidator.action "{id}" is invalid. Unable to find such an action in the current controller.' => 'CCaptchaValidator.action "{id}" ir nekorekts. Darbība netika atrasta pašreizējā kontrolierī.',
  'CDbAuthManager.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbAuthManager.connectionID "{id}" ir nekorekts. Pārbaudiet, ka tas norāda uz CDbConnection komponentes ID.',
  'CDbCache.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbCache.connectionID "{id}" ir nekorekts. Pārbaudiet, ka tas norāda uz CDbConnection komponentes ID.',
  'CDbCacheDependency.sql cannot be empty.' => 'CDbCacheDependency.sql ir jābūt aizpildītam.',
  'CDbCommand failed to execute the SQL statement: {error}' => 'CDbCommand neizdevās izpildīt SQL vaicājumu: {error}',
  'CDbCommand failed to prepare the SQL statement: {error}' => 'CDbCommand neizdevās sagatavot SQL vaicājumu: {error}',
  'CDbConnection does not support reading schema for {driver} database.' => 'CDbConnection neatbalsta shēmas nolasīšanu no {driver} datu bāzes.',
  'CDbConnection failed to open the DB connection: {error}' => 'CDbConnection neizdevās izveidot savienojumu ar datu bāzi: {error}',
  'CDbConnection is inactive and cannot perform any DB operations.' => 'CDbConnection savienojums ir neaktīvs un nevar izpildīt pieprasījumus uz datu bāzi.',
  'CDbConnection.connectionString cannot be empty.' => 'Parametrs CDbConnection.connectionString ir jābūt aizpildītam.',
  'CDbDataReader cannot rewind. It is a forward-only reader.' => 'CDbDataReader nevar nolasīt iepriekšējos datus. Šī komponente var nolasīt datus tikai uz priekšu.',
  'CDbHttpSession.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbHttpSession.connectionID "{id}" ir nekorekts. Pārbaudiet, ka tas norāda uz CDbConnection komponentes ID.',
  'CDbLogRoute.connectionID "{id}" does not point to a valid CDbConnection application component.' => 'CDbLogRoute.connectionID "{id}" ir nekorekts. Pārbaudiet, ka tas norāda uz CDbConnection komponentes ID.',
  'CDbMessageSource.connectionID is invalid. Please make sure "{id}" refers to a valid database application component.' => 'CDbMessageSource.connectionID "{id}" ir nekorekts. Pārbaudiet, ka tas norāda uz CDbConnection komponentes ID.',
  'CDbTransaction is inactive and cannot perform commit or roll back operations.' => 'CDbTransaction ir neaktīva, nav iespējams veikt atdošanas (commit) un atrites (rollback) operācijas.',
  'CDirectoryCacheDependency.directory cannot be empty.' => 'CDirectoryCacheDependency.directory ir jābūt aizpildītam.',
  'CEAcceleratorCache requires PHP eAccelerator extension to be loaded, enabled or compiled with the "--with-eaccelerator-shared-memory" option.' => 'CEAcceleratorCache komponentei ir nepieciešams PHP paplašinājums eAccelerator, kas ir kompilēts ar konfigurācijas opciju "--with-eaccelerator-shared-memory".',
  'CFileCacheDependency.fileName cannot be empty.' => 'CFileCacheDependency.fileName ir jābūt aizpildītam.',
  'CFileLogRoute.logPath "{path}" does not point to a valid directory. Make sure the directory exists and is writable by the Web server process.' => 'Ceļš CFileLogRoute.logPath "{path}" norāda uz nekoretu direktoriju. Pārbaudiet, ka direktorijs eksistē un ka tīmekļa servera procesam ir tiesības rakstīt norādītajā direktorijā.',
  'CFilterChain can only take objects implementing the IFilter interface.' => 'CFilterChain var saturēt tikai objektus, kas implementē interfeisu IFilter.',
  'CFlexWidget.baseUrl cannot be empty.' => 'CFlexWidget.baseUrl ir jābūt aizpildītam.',
  'CFlexWidget.name cannot be empty.' => 'CFlexWidget.name ir jābūt aizpildītam.',
  'CGlobalStateCacheDependency.stateName cannot be empty.' => 'CGlobalStateCacheDependency.stateName ir jābūt aizpildītam.',
  'CHttpCookieCollection can only hold CHttpCookie objects.' => 'CHttpCookieCollection var saturēt tikai objektus ar tipu CHttpCookie.',
  'CHttpRequest is unable to determine the entry script URL.' => 'CHttpRequest neizdevās noteikt ieejošā skripta URL.',
  'CHttpRequest is unable to determine the path info of the request.' => 'CHttpRequest neizdevās noteikt pieprasījuma ceļu.',
  'CHttpRequest is unable to determine the request URI.' => 'CHttpRequest neizdevās noteikt pieprasījuma URI.',
  'CHttpSession.cookieMode can only be "none", "allow" or "only".' => 'CHttpSession.cookieMode var saturēt tikai vērtības "none", "allow" vai "only".',
  'CHttpSession.gcProbability "{value}" is invalid. It must be an integer between 0 and 100.' => 'CHttpSession.gcProbability vērtība "{value}" ir nekorekta. Tai ir jābūt intervālā no 0 līdz 100.',
  'CHttpSession.savePath "{path}" is not a valid directory.' => 'CHttpSession.savePath ceļš "{path}" nav korekts direktorijs.',
  'CMemCache server configuration must be an array.' => 'CMemCache servera konfigurācijai ir jābūt masīvam.',
  'CMemCache server configuration must have "host" value.' => 'CMemCache servera konfigurācijas masīvam ir jāsatur elements "host".',
  'CMultiFileUpload.name is required.' => 'CMultiFileUpload.name ir obligāts.',
  'CProfileLogRoute found a mismatching code block "{token}". Make sure the calls to Yii::beginProfile() and Yii::endProfile() be properly nested.' =