<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @author Srinivasan A Paul Joseph <sapauljoseph@gmail.com>
 * @version $Id: $
 */
return array (
  'Alias "{alias}" is invalid. Make sure it points to an existing PHP file and the file is readable.' => '"{alias}" மாற்றுப்பெயர் சரியானது இல்லை. சரியான PHP கோப்புக்கு சுட்டிக்காட்டப்பட்டிருக்கிறதா என்று பார்க்கவும்.',
  'Alias "{alias}" is invalid. Make sure it points to an existing directory.' => '"{alias}" மாற்றுப்பெயர் சரியானது இல்லை. சரியான கோர்வைக்கு சுட்டிக்காட்டப்பட்டிருக்கிறதா என்று பார்க்கவும்.',
  'Application Log' => 'பயன்பாட்டின் தடங்கள்',
  'CDbConnection failed to open the DB connection.' => 'CDbConnection ஆல் தகவல்தளத்தை திறக்க இயலவில்லை.',
  'CDbTestFixture.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbTestFixture.connectionID "{id}" சரியானது இல்லை. CDbConnection இன் ID க்கு சுட்டிக்காட்டப்பட்டிருக்கிறதா என்று பார்க்கவும்.',
  'CTypedMap<{type}> can only hold objects of {type} class.' => 'CTypedMap<{type}> ஆல் {type} உடற்கூறுகளை மட்டுமே கொண்டிருக்க இயலும்.',
  'CWinCache requires PHP wincache extension to be loaded.' => 'CWinCache PHP இன் wincache நீட்சியைச் சார்ந்து இருக்கின்றது.',
  'CWinCache user cache is disabled. Please set wincache.ucenabled to On in your php.ini.' => 'CWinCache பயனாளர் சேமிப்பு முடக்கப்பட்டுள்ளது. உங்களின் php.ini கோப்பில் wincache.ucenabled செயலிலுள்ளதா என்று சரிபார்க்கவும்.',
  'Failed to initialize the mcrypt module.' => 'mcrypt நீட்சியை செயலாக்க இயலவில்லை.',
  'Failed to set unsafe attribute "{attribute}".' => 'பாதுகாப்பில்லாத "{attribute}" ஐ கொடுக்க இயலாது.',
  'GD and FreeType PHP extensions are required.' => 'PHP இன் GD மற்றும் FreeType நீட்சிகள் வேண்டும்.',
  'Resetting PK sequence is not supported.' => 'PK வரிசையை மாற்றுவது செயலாக்க இயலாது.',
  'Setting integrity check is not supported.' => 'கெடுதலில்லாமை சரிபார்ப்பை செயலாக்க இயலாது.',
  'The "range" property must be specified with a list of values.' => '"range" தண்மை மதிப்பு வரிசைகளைக் கொண்டிருக்க வேண்டும்.',
  'The pattern for day of the week must be "E", "EE", "EEE", "EEEE", "EEEEE", "e", "ee", "eee", "eeee", "eeeee", "c", "cccc" or "ccccc".' => 'வாரத்தின் கிழமையைக் குறிக்கும் மாதிரி "E", "EE", "EEE", "EEEE", "EEEEE", "e", "ee", "eee", "eeee", "eeeee", "c", "cccc" அல்லது "ccccc" ஆக இருக்க வேண்டும்.',
  'The pattern for month must be "M", "MM", "MMM", "MMMM", "L", "LL", "LLL" or "LLLL".' => 'மாதத்தைக் குறிக்கும் மாதிரி "M", "MM", "MMM", "MMMM", "L", "LL", "LLL" அல்லது "LLLL" ஆக இருக்க வேண்டும்.',
  'The requested view "{name}" was not found.' => 'நீங்கள் வேண்டிய "{name}" காட்சி காணக் கிடைக்கவில்லை.',
  'Unable to import "{alias}". Please check your server configuration to make sure you are allowed to change PHP include_path.' => '"{alias}" ஐ பதிவிறக்க இயலவில்லை. PHP இன் include_path ஐ உங்களால் மாற்ற முடியுமா என்று உங்களின் வழங்கியின் பண்புகளில் சரிபார்க்கவும்.',
  'Unknown type "{type}".' => 'தெரியாத "{type}" வகை.',
  'Your request is invalid.' => 'உங்களின் வேண்டுகோள் சரியானது இல்லை.',
  '{attribute} cannot accept more than {limit} files.' => '{limit} கோப்புகளுக்கு மேல் {attribute} ஏற்றுக்கொள்ளாது.',
  '{attribute} is in the list.' => '{attribute} வரிசையிலுள்ளது.',
  '{className} does not support flushValues() functionality.' => '{className} உடற்கூறு flushValues() பயன்பாட்டை கொண்டிருக்கவில்லை.',
  'CMultiFileUpload.name is required.' => 'CMultiFileUpload.name முக்கியமானது.',
  'CSecurityManager.validation must be either "MD5" or "SHA1".' => 'CSecurityManager.validation இன் மதிப்பு "MD5" அல்லது "SHA1" ஆக இருக்க வேண்டும்.',
  'Column "{column} does not exist in table "{table}".' => '"{table}" பட்டியலில் "{column}" விவரம் இல்லை.',
  0 => 0,
  'The pattern for day of the week must be "E", "EE", "EEE", "EEEE" or "EEEEE".' => 'வாரத்தின் கிழமையைக் குறிக்கும் மாதிரி "E", "EE", "EEE", "EEEE" அல்லது "EEEEE" ஆக இருக்க வேண்டும்.',
  'The pattern for month must be "M", "MM", "MMM", or "MMMM".' => 'மாதத்தைக் குறிக்கும் மாதிரி "M", "MM", "MMM", அல்லது "MMMM" ஆக இருக்க வேண்டும்.',
  'The relation "{relation}" in active record class "{class}" is specified with an invalid foreign key "{key}". The foreign key does not point to either joining table.' => 'ActiveRecord இன் "{class}" உடற்கூறிலுள்ள "{relation}" சார்பு தவறான "{key}" அயல் குறியீட்டுடன் (foreign key) வரையறுக்கப்பட்டிருக்கின்றது. இந்த அயல் குறியீடு இணைக்கப்படும் எந்த பட்டியலையும் குறிப்பிடவில்லை.',
  'The requested view "{name}" is not found.' => 'நீங்கள் வேண்டிய "{name}" காட்சி இந்த தளத்தில் இல்லை.',
  '{className} does not support flush() functionality.' => 'flush() செயலை {className} ஒத்துக்கொள்ளாது.',
  '"{path}" is not a valid directory.' => '"{path}" சரியான கோப்புத் தொகுப்பு இல்லை.',
  '&lt; Previous' => '&lt; முந்தையது',
  '&lt;&lt; First' => '&lt;&lt; முதலாவது',
  'Active Record requires a "db" CDbConnection application component.' => 'ActiveRecord இயங்க "தகவல் தள" CDbConnection அங்கத்தின் இணைப்பு இருக்க வேண்டும்.',
  'Active record "{class}" has an invalid configuration for relation "{relation}". It must specify the relation type, the related active record class and the foreign key.' => 'ActiveRecord "{class}" தவறாக அமைக்கப்பட்ட "{relation}" சார்பைக் கொண்டுள்ளது. சார்பு வகை, சார்ந்துள்ள ActiveRecord class மற்றும் அயல் சாவி (Foreign Key) கொடுத்திருக்க வேண்டும்.',
  'Active record "{class}" is trying to select an invalid column "{column}". Note, the column must exist in the table or be an expression with alias.' => 'ActiveRecord "{class}" தவறான "{column}" விவரத்தை தேர்ந்தெடுக்க முயற்சிக்கின்றது. குறிப்பு: தேர்ந்தெடுக்கும் விவரம் பட்டியலில் இருப்பதாகவோ அல்லது பட்டியலிலுள்ள வேறொரு விவரத்திற்கு மாற்றுப் பெயராகவோ இருத்தல் வேண்டும்.',
  'Active record class "{class}" does not have a scope named "{scope}".' => 'ActiveRecord இன் "{class}" கூட்டுறுப்பு "{scope}" என்ற செயல்மட்டத்தை வரையறுக்கவில்லை.',
  'Alias "{alias}" is invalid. Make sure it points to an existing directory or file.' => 'மாற்றுப்பெயர் "{alias}" தவறானது. கொடுத்துள்ள மாற்றுப்பெயர் ஏதோ ஒரு கோப்பையோ அல்லது கோர்வையையோ குறிப்பிடுகின்றதா என்று சோதித்துப் பார்க்கவும்.',
  'Application base path "{path}" is not a valid directory.' => 'தளத்தின் அடிப்படை முகவரி "{path}" ஒரு கோர்வையைக் குறிக்கவில்லை.',
  'Application runtime path "{path}" is not valid. Please make sure it is a directory writable by the Web server process.' => 'தளத்தின் இயங்கு நேர முகவரி "{path}" தவறானது. இந்த முகவரி இணைய வழங்குதளத்தால் எழுதப்படக்கூடிய கோர்வையைக் குறிக்கின்றதா என்று சரிபார்க்கவும்.',
  'Authorization item "{item}" has already been assigned to user "{user}".' => 'அனுமதியளிக்கும் "{item}" பொருளில் ஏற்கனவே "{user}" பயனாளருக்கு அனுமதியளிக்கப்பட்டுள்ளது.',
  'Base path "{path}" is not a valid directory.' => 'தளத்தின் அடிப்படை முகவரி "{path}" சரியான கோர்வையைக் குறிக்கவில்லை.',
  'CApcCache requires PHP apc extension to be loaded.' => 'PHP-இன் apc உள்ளிணைப்பு இருந்தால்தான் CApcCache இயங்க முடியும்.',
  'CAssetManager.basePath "{path}" is invalid. Please make sure the directory exists and is writable by the Web server process.' => 'CAssetManager.basePath முகவரி "{path}" தவறானது. இந்த முகவரி இணைய வழங்குதளத்தால் எழுதப்படக்கூடிய கோர்வையைக் குறிக்கின்றதா என்று சரிபார்க்கவும்.',
  'CCacheHttpSession.cacheID is invalid. Please make sure "{id}" refers to a valid cache application component.' => 'CCacheHttpSession.cacheID தவறாக உள்ளது. குறியீடு "{id}" சரியான சேமிப்பு (cache) அங்கத்தைக் குறிக்கின்றதா என்று சரிபார்க்கவும்.',
  'CCaptchaValidator.action "{id}" is invalid. Unable to find such an action in the current controller.' => 'CCaptchaValidator.action இன் "{id}" தவறானது. தற்போதைய கட்டுப்பாட்டில் அத்தகைய செயல் குறிப்பிடப்படவில்லை.',
  'CDbAuthManager.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbAuthManager.connectionID இன் "{id}" தவறானது. அது CDbConnection அங்கத்தின் குறியீட்டைக் குறிக்கின்றதா என்று சரிபார்க்கவும்.',
  'CDbCache.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbCache.connectionID இன் "{id}" தவறானது. அது CDbConnection அங்கத்தின் குறியீட்டைக் குறிக்கின்றதா என்று சரிபார்க்கவும்.',
  'CDbCacheDependency.sql cannot be empty.' => 'CDbCacheDependency.sql காலியாக இருக்கக்கூடாது.',
  'CDbCommand failed to execute the SQL statement: {error}' => 'CDbCommand ஆல் கொடுத்த SQL கட்டளையை செயல்படுத்த முடியவில்லை: {error}',
  'CDbCommand failed to prepare the SQL statement: {error}' => 'CDbCommand ஆல் கொடுத்த SQL கட்டளையை தயார்படுத்த முடியவில்லை: {error}',
  'CDbConnection does not support reading schema for {driver} database.' => 'CDbConnection இணைப்பு {driver} இயக்கி செயல்படுத்தும் தகவல் தளத்தின் அடிக்கூறை (schema) படிக்க இயலாது.',
  'CDbConnection failed to open the DB connection: {error}' => 'CDbConnection ஆல் தகவல் தளத்திற்கு இணைப்பை உருவாக்க முடியவில்லை: {error}',
  'CDbConnection is inactive and cannot perform any DB operations.' => 'CDbConnection இயங்கும் நிலையில் இல்லாததால் எந்த தகவல்தள செயலையும் செய்ய இயலாது.',
  'CDbConnection.connectionString cannot be empty.' => 'CDbConnection.connectionString காலியாக இருக்கக்கூடாது.',
  'CDbDataReader cannot rewind. It is a forward-only reader.' => 'CDbDataReader பின்னோக்கி படிக்காது. முன்னோக்கி படிக்க மட்டுமே வரையறுக்கப்பட்டுள்ளது.',
  'CDbHttpSession.connectionID "{id}" is invalid. Please make sure it refers to the ID of a CDbConnection application component.' => 'CDbHttpSession.connectionID இன் "{id}" தவறானது. அது CDbConnection அங்கத்தின் குறியீட்டைக் குறிக்கின்றதா என்று சரிபார்க்கவும்.',
  'CDbLogRoute.connectionID "{id}" does not point to a valid CDbConnection application component.' => 'CDbLogRoute.connectionID இன் "{id}" சரியான CDbConnection அங்கத்தின் குறியீட்டைக் குறிக்கவில்லை.',
  'CDbMessageSource.connectionID is invalid. Please make sure "{id}" refers to a valid database application component.' => 'CDbMessageSource.connectionID தவறானது. "{id}" சரியான தகவல்தள அங்கத்தைக் குறிக்கின்றதா என்று சோதிக்கவும்.',
  'CDbTransaction is inactive and cannot perform commit or roll back operations.' => 'CDbTransaction செயலில் இல்லாததால் கட்டளைக் குழுக்களை இயக்கவோ திருப்பி விடவோ இயலாது.',
  'CDirectoryCacheDependency.directory cannot be empty.' => 'CDirectoryCacheDependency.directory காலியாக இருக்கக்கூடாது.',
  'CEAcceleratorCache requires PHP eAccelerator extension to be loaded, enabled or compiled with the "--with-eaccelerator-shared-memory" option.' => 'CEAcceleratorCache ஐ செயலாக்க PHP இன் eAccelerator உள்ளிணைப்பு செயலாக்கப்பட்டோ, இயங்குநிலையிலோ அல்லது "--with-eaccelerator-shared-memory" அமைப்பின்மூலம் ஒன்றாக்கப்பட்டோ இருக்க வேண்டும்.',
  'CFileCacheDependency.fileName cannot be empty.' => 'CFileCacheDependency.fileName காலியாக இருக்கக்கூடாது.',
  'CFileLogRoute.logPath "{path}" does not point to a valid directory. Make sure the directory exists and is writable by the Web server process.' => 'CFileLogRoute.logPath இன் "{path}" முகவரி சரியான கோர்வையைக் குறிக்கவில்லை. இந்த முகவரி இணைய வழங்குதளத்தால் எழுதப்படக்கூடிய கோர்வையைக் குறிக்கின்றதா என்று சரிபார்க்கவும்.',
  'CFilterChain can only take objects implementing the IFilter interface.' => 'CFilterChain ஆல் IFilter இடைமுகப்பை வரையறுத்துள்ள பொருட்களை மட்டும்தான் உபயோகிக்க முடியும்.',
  'CFlexWidget.baseUrl cannot be empty.' => 'CFlexWidget.baseUrl காலியாக இருக்கக்கூடாது.',
  'CFlexWidget.name cannot be empty.' => 'CFlexWidget.name காலியாக இருக்கக்கூடாது.',
  'CGlobalStateCacheDependency.stateName cannot be empty.' => 'CGlobalStateCacheDependency.stateName காலியாக இருக்கக்கூடாது.',
  'CHttpCookieCollection can only hold CHttpCookie objects.' => 'CHttpCookieCollection ஆல் CHttpCookie பொருட்களை மட்டும்தான் உள்ளடக்க முடியும்.',
  'CHttpRequest is unable to determine the entry script URL.' => 'CHttpRequest ஆல் உள்நுழை நிரலின் முகவரியை கண்டுபிடிக்க இயலவில்லை.',
  'CHttpRequest is unable to determine the path info of the request.' => 'CHttpRequest ஆல் வேண்டுகோளின் சரியான முகவரியை நிர்ணயிக்க முடியவில்லை.',
  'CHttpRequest is unable to determine the request URI.' => 'CHttpRequest ஆல் வேண்டுகோளின் சரியான முகவரியை நிர்ணயிக்க முடியவில்லை.',
  'CHttpSession.cookieMode can only be "none", "allow" or "only".' => 'CHttpSession.cookieMode இல் "none", "allow" அல்லது "only" மதிப்புகளை மட்டுமே இருத்தல் வேண்டும்.',
